export const REQUEST_API_LIST = 'REQUEST_API_LIST';
export const RECEIVE_API_LIST = 'RECEIVE_API_LIST';

export const REQUEST_API_RECORD = 'REQUEST_API_RECORD';
export const RECEIVE_API_RECORD = 'RECEIVE_API_RECORD';
